<#
.SYNOPSIS
  Bundles graph.yml and the projects/*.yml files it lists into graph-data.js.

.DESCRIPTION
  index.html fetches the YAML files when served over HTTP, but browsers block
  those fetches for pages opened straight from disk (file://). graph-data.js
  carries the same YAML text as a plain <script>, which file:// pages can
  load, so the graph works when index.html is double-clicked.

  Re-run this after editing graph.yml or any projects/*.yml file.
  When the page is served, the fetched YAML wins; the bundle is only a fallback.
#>
$ErrorActionPreference = "Stop"
$root = $PSScriptRoot
$utf8 = New-Object System.Text.UTF8Encoding($false)

$manifestPath = Join-Path $root "graph.yml"
$manifest = [IO.File]::ReadAllText($manifestPath)
$files = [ordered]@{ "graph.yml" = $manifest }

foreach ($line in ($manifest -split "`n")) {
    if ($line -match '^\s*file:\s*"?([^"\s]+)"?\s*$') {
        $rel = $Matches[1]
        $files[$rel] = [IO.File]::ReadAllText((Join-Path $root $rel))
    }
}

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine("// GENERATED by Build-GraphData.ps1 - do not edit by hand.")
[void]$sb.AppendLine("// Bundled copy of graph.yml + projects/*.yml so index.html works from file://.")
[void]$sb.AppendLine("window.LFS_YAML = {")
foreach ($entry in $files.GetEnumerator()) {
    $key = ($entry.Key | ConvertTo-Json -Compress)
    $val = ($entry.Value | ConvertTo-Json -Compress)
    $val = $val.Replace("</", "<\/")
    [void]$sb.AppendLine("  ${key}: ${val},")
}
[void]$sb.AppendLine("};")

$out = Join-Path $root "graph-data.js"
[IO.File]::WriteAllText($out, $sb.ToString(), $utf8)
Write-Host ("graph-data.js written: {0} files, {1:N0} bytes" -f $files.Count, (Get-Item $out).Length)
