<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>annotations</Nullable>
		<ImplicitUsings>disable</ImplicitUsings>
		<OutputType>Library</OutputType>
		<NoWarn>CS1998</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Xeption" Version="2.9.0" />
	</ItemGroup>

</Project>
